const userTypes = {
  FETCH_PROPERTY: 'FETCH_PROPERTY',
  // Access
  FETCH_ACCESS: 'FETCH_ACCESS',
  RESET_FETCH_ACCESS: 'RESET_FETCH_ACCESS',
  // Contact
  FETCH_CONTACT: 'FETCH_CONTACT',
  RESET_FETCH_CONTACT: 'RESET_FETCH_CONTACT',
  // Decription
  FETCH_DESCRIPTION: 'FETCH_DESCRIPTION',
  RESET_FETCH_DESCRIPTION: 'RESET_FETCH_DESCRIPTION',
  // Document
  FETCH_DOCUMENT: 'FETCH_DOCUMENT',
  RESET_FETCH_DOCUMENT: 'RESET_FETCH_DOCUMENT',
  // Elevator
  FETCH_ELEVATOR: 'FETCH_ELEVATOR',
  RESET_FETCH_ELEVATOR: 'RESET_FETCH_ELEVATOR',
  // Generator
  FETCH_GENERATOR: 'FETCH_GENERATOR',
  RESET_FETCH_GENERATOR: 'RESET_FETCH_GENERATOR',
  // LockBox
  FETCH_LOCKBOX: 'FETCH_LOCKBOX',
  RESET_FETCH_LOCKBOX: 'RESET_FETCH_LOCKBOX',
  // Matterport
  FETCH_MATTERPORT: 'FETCH_MATTERPORT',
  RESET_FETCH_MATTERPORT: 'RESET_FETCH_MATTERPORT',
  // Photo
  FETCH_PHOTO: 'FETCH_PHOTO',
  RESET_FETCH_PHOTO: 'RESET_FETCH_PHOTO',
  // Precaution
  FETCH_PRECAUTION: 'FETCH_PRECAUTION',
  RESET_FETCH_PRECAUTION: 'RESET_FETCH_PRECAUTION',
  // PreExistingDamage
  FETCH_PREEXISTINGDAMAGE: 'FETCH_PREEXISTINGDAMAGE',
  RESET_FETCH_PREEXISTINGDAMAGE: 'RESET_FETCH_PREEXISTINGDAMAGE',
  // Utility
  FETCH_UTILITY: 'FETCH_UTILITY',
  RESET_FETCH_UTILITY: 'RESET_FETCH_UTILITY',
  // Question
  FETCH_QUESTION: 'FETCH_QUESTION',
  ADD_ANSWER_SUCCESS: 'ADD_ANSWER_SUCCESS',
  RESET_ADDANSWER_FORMS: 'RESET_ADDANSWER_FORMS',
  RESET_FETCH_QUESTION: 'RESET_FETCH_QUESTION',
  // Support
  FETCH_SUPPORT: 'FETCH_SUPPORT',
  RESET_FETCH_SUPPORT: 'RESET_FETCH_SUPPORT',

  // Reset Fetch
  RESET_FETCH_ALL: 'RESET_FETCH_ALL',
  // Errors
  SET_ERRORS: 'SET_ERRORS',
};

export default userTypes;
